<?php

namespace TaskManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
//use TaskManagerBundle\Entity\Projects;
use TaskManagerBundle\Entity\Tasks;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
	
}
