<?php

namespace TaskManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends EntityRepository
{
	public function getNumberOfTasks($id)
	{
		$qb = $this->createQueryBuilder('p')
				   ->where('p.projects = :id')
				   ->setParameter('id', $id)
				   ->getQuery();
		return count($qb->getResult());
	}
	
	public function getNumberOfCompletedTasks($id)
	{ 
		$qb = $this->createQueryBuilder('p')
				   ->where('p.projects = :id','p.completed = 1')
				   ->setParameter('id', $id)
				   ->getQuery(); 
		return count($qb->getResult());
	}
	
	public function getPercentComplete($id)
	{
		$numberOfTasks = $this->getNumberOfTasks($id);
		$numberOfCompletedTasks = $this->getNumberOfCompletedTasks($id); 
		
		if($numberOfTasks == 0)
				return 100;
		
		return ($numberOfCompletedTasks / $numberOfTasks) * 100;
	}
	
}
